spring:
  application:
    name: hello-spring-boot
    # thymeleaf:
    #   cache: false
    #   mode: HTML
    #   encoding: UTF-8
    #   servlet:
    #     content-type: text/html
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.168.208;database=myshop
    username: sa
    password: 1234abcd.
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.funtl.hello.spring.boot.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081
  servlet:
    context-path: /boot

